Html css files
DavyKn/Wangari_Tribute pull request #1
Opened 2022-03-28 21:36 UTC by DavyKn

My Tribute page , files are in CSS and CSS styled

2022-03-28 22:23 UTC, DavyKn reviewed
~ code look okay
~No Linter errors 👍 
~Next time include media query for a better view on smaller screens👌

2022-03-28 22:23 UTC, DavyKn commented on index.html
> +          <a class="tribute-link" href="https://en.wikipedia.org/wiki/Wangari_Maathai" rel="noreferrer">Wikipedia</a>
instead of rel="noreferrer"  use  rel="noopener": This is the new version

2022-03-28 22:58 UTC, OLIPLICHE requested changes
Hi @DavyKn , 

Good job so far!
There are some issues that you still need to work on for your project to be approved.  but you are almost there!

## Highlights


## Required Changes ♻️
- Please you need to write at least 2 comments in the review instead of 1
- Please phrase the comments politely, as suggestions instead of orders, and include ("Please", "Kindly")
- Please, you need to be explicit in telling the students the reason "why " you asking for changes

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-28 22:58 UTC, OLIPLICHE commented on index.html
> +          <a class="tribute-link" href="https://en.wikipedia.org/wiki/Wangari_Maathai" rel="noreferrer">Wikipedia</a>
- [ ] Hi @DavyKn, Please phrase your comments politely, as suggestions instead of orders. Example: Please, I think it would be better to use ......

2022-03-29 15:55 UTC, DavyKn reviewed
Hi @DavyKn ,

Good job so far!
I have commented on some few issues that you can consider adapting in your future projects, I think they will be able to improve your site responsiveness. but you are almost there!

Highlights
Optional Changes ♻️
~use of media query.
~use of rel="noopener"




 Check the comments under the review.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-03-29 15:55 UTC, DavyKn commented on style.css
> +}
- [ ] Kindly,I think you should make use of media query. They will make your site be responsive hence adapting to different screen sizes.

2022-03-29 16:02 UTC, OLIPLICHE approved these changes
Hi @DavyKn, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-29 16:06 UTC, merged